//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> DateLogout { get; set; }
        public Nullable<System.DateTime> DateExit { get; set; }
        public int TypeCloseAppID { get; set; }
    
        public virtual TypeCloseApp TypeCloseApp { get; set; }
        public virtual Users Users { get; set; }
    }
}
