//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmenitiesCabinType
    {
        public int Id { get; set; }
        public int CabinTypeID { get; set; }
        public int AmenityID { get; set; }
    
        public virtual Amenities Amenities { get; set; }
        public virtual CabinTypes CabinTypes { get; set; }
    }
}
